# Generated by Django 6.0.3 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='specialisation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
