# Generated by Django 6.0.3 on 2026-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
