# Generated by Django 6.0.3 on 2026-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_department_specialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='skills',
            field=models.CharField(blank=True, help_text='e.g. AWS, Django, React', max_length=255, null=True),
        ),
    ]
