# Generated by Django 6.0.3 on 2026-04-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_members_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_type',
        ),
        migrations.DeleteModel(
            name='TeamType',
        ),
    ]
